### ISSUE TITLE
onChange Event to be triggered if value modified externaly

### ISSUE THREAD

**Issue by 80leaves** [EnotionZ/gpio#16]
Hey, 
I'm not quite sure if this is actually a "feature request" or a "bug". If I modify the value of the gpio-pin externaly, for example with `gpio -g write 3 0` the onChange event is not triggered. If it is done via the nodeJS app it works fine.

**Comment by rzr** [comment]
I guess that would work for input gpio, for output I am not sure it can be know from outside context.

**Comment by EnotionZ** [comment]
Just confirming, we only watch for file changes with input direction. For the output direction, we emit the event as soon as we receive the call from the internal context. This saves on processing power by reading the value from sysfs at certain intervals.

I guess technically it's possible to watch for changes in the output direction, but it's outside the scope of this library. Filing as _wontfix_.
