### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (3)

### ISSUE THREAD

**Issue by uAliFurkanY** [EnotionZ/gpio#62]
This is an undocumented change. Please update the official documentation. The example code no longer works.

Now we have to make the pin number a string.

**Comment by Maximvdw** [comment]
Note: It also means that the "value" that is set when setting the GPIO value should also be a number.
https://github.com/EnotionZ/gpio/blob/master/lib/gpio.js#L234-L235

**Comment by ali-tafakkori** [comment]
any update?
